function [connways_eqtags_filt,...
	dx_all_mm,...
	dy_all_mm,...
	diag_all_mm,...
	length_all_mm,...
	area_all_mm2,...
	dx_node_mm,...
	dy_node_mm,...
	diag_node_mm,...
	dx_line_v_mm,...
	dy_line_v_mm,...
	diag_line_v_mm,...
	dx_area_v_mm,...
	dy_area_v_mm,...
	diag_area_v_mm,...
	length_lines_v_mm,...
	length_areas_v_mm,...
	area_v_mm2]=...
	plotosmdata_getdata_filterout(...
	connways_eqtags,...
	connways_eqtags_filt,...
	mindimx,...
	mindimy,...
	mindiag,...
	minlength,...
	minarea,...
	filter_nla_separatly,...
	force_keep_data,...
	obj_eqtags_ioeqt,...
	msg)
% Filter out small objects in connways_eqtags and add the rest to connways_eqtags_filt
% Used in:	plotosmdata_getdata
%				plotosmdata_getdata_symbols
%				plotosmdata_getdata_texts
% Special case: minarea=-999999: The areas are not filtered, regardless of the other limit values.

global GV GV_H WAITBAR

try
	
	% Calculate the dimensions of nodes and ways:
	[  xmin_all_mm ,xmax_all_mm ,ymin_all_mm ,ymax_all_mm ,...
		xmin_node_mm,xmax_node_mm,ymin_node_mm,ymax_node_mm,...
		xmin_line_mm,xmax_line_mm,ymin_line_mm,ymax_line_mm,...
		xmin_area_mm,xmax_area_mm,ymin_area_mm,ymax_area_mm]=...
		connways_dim(connways_eqtags);
	dx_all_mm			= xmax_all_mm-xmin_all_mm;
	dy_all_mm			= ymax_all_mm-ymin_all_mm;
	diag_all_mm			= sqrt(dx_all_mm.^2+dy_all_mm.^2);
	dx_node_mm			= xmax_node_mm-xmin_node_mm;
	dy_node_mm			= ymax_node_mm-ymin_node_mm;
	diag_node_mm		= sqrt(dx_node_mm.^2+dy_node_mm.^2);
	dx_line_v_mm		= xmax_line_mm-xmin_line_mm;
	dy_line_v_mm		= ymax_line_mm-ymin_line_mm;
	diag_line_v_mm		= sqrt(dx_line_v_mm.^2+dy_line_v_mm.^2);
	dx_area_v_mm		= xmax_area_mm-xmin_area_mm;
	dy_area_v_mm		= ymax_area_mm-ymin_area_mm;
	diag_area_v_mm		= sqrt(dx_area_v_mm.^2+dy_area_v_mm.^2);
	[  length_all_mm,...											% length_mm
		length_lines_v_mm,...									% length_lines_v_mm
		length_areas_v_mm]	= ...								% length_areas_v_mm
		connways_length(connways_eqtags);
	if minarea>0
		[  area_all_mm2,...											% area_mm2
			area_v_mm2]	= ...											% area_v_mm2
			connways_area(connways_eqtags,msg);
	else
		% Calculating areas can be time-consuming. Skip this step if it is not necessary:
		area_v_mm2		= zeros(size(connways_eqtags.areas,1),1);
		area_all_mm2	= 0;
	end
	
	% Assign the nodes:
	% Nodes are not filtered out if minlength>0 or minarea>0.
	if ~isempty(connways_eqtags.nodes)
		if    force_keep_data||                (...
				(dx_node_mm  >=mindimx  )&&...
				(dy_node_mm  >=mindimy  )&&...
				(diag_node_mm>=mindiag  )&&...
				(filter_nla_separatly~=0)     )||(...
				(dx_all_mm   >=mindimx  )&&...
				(dy_all_mm   >=mindimy  )&&...
				(diag_all_mm >=mindiag  )&&...
				(filter_nla_separatly==0)        )
			% Merge connways_eqtags with connways_eqtags_filt:
			if isempty(connways_eqtags_filt.nodes)
				connways_eqtags_filt.nodes	= connways_eqtags.nodes;
			else
				connways_eqtags_filt.nodes.xy	= [...
					connways_eqtags_filt.nodes.xy;connways_eqtags.nodes.xy];
			end
		end
	end
	
	% Assign the lines:
	% Lines are not filtered out if minarea>0.
	for k_line=1:size(connways_eqtags.lines,1)
		% Waitbar:
		if etime(clock,WAITBAR.t1)>=GV.waitbar_dtupdate
			WAITBAR.t1	= clock;
			set(GV_H.text_waitbar,'String',sprintf('%s lines: %g/%g',msg,k_line,size(connways_eqtags.lines,1)));
			drawnow;
		end
		if    force_keep_data||(...
				(dx_line_v_mm(k_line,1)     >=mindimx  )&&...
				(dy_line_v_mm(k_line,1)     >=mindimy  )&&...
				(diag_line_v_mm(k_line,1)   >=mindiag  )&&...
				(length_lines_v_mm(k_line,1)>=minlength)&&...
				(filter_nla_separatly~=0               )     )||(...
				(dx_all_mm                  >=mindimx  )&&...
				(dy_all_mm                  >=mindimy  )&&...
				(diag_all_mm                >=mindiag  )&&...
				(length_all_mm              >=minlength)&&...
				(filter_nla_separatly==0               )     )
			% Merge connways_eqtags with connways_eqtags_filt, without connecting lines:
			connways_eqtags.lines(k_line,1).tag	= obj_eqtags_ioeqt;
			if isempty(connways_eqtags_filt.lines)
				connways_eqtags_filt.lines				= connways_eqtags.lines(k_line,1);
				connways_eqtags_filt.lines_isouter	= connways_eqtags.lines_isouter(k_line,1);
				connways_eqtags_filt.lines_isinner	= connways_eqtags.lines_isinner(k_line,1);
				connways_eqtags_filt.lines_relid		= connways_eqtags.lines_relid(k_line,1);
				connways_eqtags_filt.xy_start			= connways_eqtags.xy_start(k_line,:);
				connways_eqtags_filt.xy_end			= connways_eqtags.xy_end(k_line,:);
				connways_eqtags_filt.lino_max			= connways_eqtags.lino_max;
			else
				connways_eqtags_filt.lines(end+1,1)				= connways_eqtags.lines(k_line,1);
				connways_eqtags_filt.lines_isouter(end+1,1)	= connways_eqtags.lines_isouter(k_line,1);
				connways_eqtags_filt.lines_isinner(end+1,1)	= connways_eqtags.lines_isinner(k_line,1);
				connways_eqtags_filt.lines_relid(end+1,1)		= connways_eqtags.lines_relid(k_line,1);
				connways_eqtags_filt.xy_start(end+1,:)			= connways_eqtags.xy_start(k_line,:);
				connways_eqtags_filt.xy_end(end+1,:)			= connways_eqtags.xy_end(k_line,:);
				connways_eqtags_filt.lino_max						= max(...
					connways_eqtags_filt.lino_max,connways_eqtags.lino_max);
			end
		end
	end
	
	% Assign the areas:
	if minarea==-999999
		% Special case: Do not filter out areas:
		for k_area=1:size(connways_eqtags.areas,1)
			connways_eqtags.areas(k_area,1).tag	= obj_eqtags_ioeqt;
		end
		connways_eqtags_filt.areas					= connways_eqtags.areas;
		connways_eqtags_filt.areas_isouter		= connways_eqtags.areas_isouter;
		connways_eqtags_filt.areas_isinner		= connways_eqtags.areas_isinner;
		connways_eqtags_filt.areas_relid			= connways_eqtags.areas_relid;
	else
		for k_area=1:size(connways_eqtags.areas,1)
			% Waitbar:
			if etime(clock,WAITBAR.t1)>=GV.waitbar_dtupdate
				WAITBAR.t1	= clock;
				set(GV_H.text_waitbar,'String',sprintf('%s areas: %g/%g',msg,k_area,size(connways_eqtags.areas,1)));
				drawnow;
			end
			if    force_keep_data                               ||(...
					(dx_area_v_mm(k_area,1)     >=mindimx  )&&...
					(dy_area_v_mm(k_area,1)     >=mindimy  )&&...
					(diag_area_v_mm(k_area,1)   >=mindiag  )&&...
					(length_areas_v_mm(k_area,1)>=minlength)&&...
					(area_v_mm2(k_area,1)       >=minarea  )&&...
					(filter_nla_separatly~=0               )     )||(...
					(dx_all_mm                  >=mindimx  )&&...
					(dy_all_mm                  >=mindimy  )&&...
					(diag_all_mm                >=mindiag  )&&...
					(length_all_mm              >=minlength)&&...
					(area_all_mm2               >=minarea  )&&...
					(filter_nla_separatly==0               )     )
				% Merge connways_eqtags with connways_eqtags_filt:
				connways_eqtags.areas(k_area,1).tag	= obj_eqtags_ioeqt;
				if isempty(connways_eqtags_filt.areas)
					connways_eqtags_filt.areas							= connways_eqtags.areas(k_area,1);
					connways_eqtags_filt.areas_isouter				= connways_eqtags.areas_isouter(k_area,1);
					connways_eqtags_filt.areas_isinner				= connways_eqtags.areas_isinner(k_area,1);
					connways_eqtags_filt.areas_relid					= connways_eqtags.areas_relid(k_area,1);
				else
					connways_eqtags_filt.areas(end+1,1)				= connways_eqtags.areas(k_area,1);
					connways_eqtags_filt.areas_isouter(end+1,1)	= connways_eqtags.areas_isouter(k_area,1);
					connways_eqtags_filt.areas_isinner(end+1,1)	= connways_eqtags.areas_isinner(k_area,1);
					connways_eqtags_filt.areas_relid(end+1,1)		= connways_eqtags.areas_relid(k_area,1);
				end
			end
		end
	end
	
catch ME
	errormessage('',ME);
end

