function r_duplicate=verify_pp_search_for_duplicate_pp(T,T_index)
% Search for duplicate project parameters which can be deleted:

try

	% Create cell arrays and vectors (faster than working with tables):
	f1_c			= T.FIELD1(:);
	f2_c			= T.FIELD2(:);
	f3_c			= T.FIELD3(:);
	f4_c			= T.FIELD4(:);
	snmc1_c		= T.SNMC1(:);
	snmc2_c		= T.SNMC2(:);
	snmc3_c		= T.SNMC3(:);
	snmc4_c		= T.SNMC4(:);

	r_duplicate			= false(height(T),1);
	for r=1:height(T)

		f1			= f1_c{r};
		f2			= f2_c{r};
		f3			= f3_c{r};
		f4			= f4_c{r};
		snmc1		= snmc1_c{r};
		snmc2		= snmc2_c{r};
		snmc3		= snmc3_c{r};
		snmc4		= snmc4_c{r};
		r1			= T_index.r1(r);
		r2			= T_index.r2(r);
		r3			= T_index.r3(r);
		r4			= T_index.r4(r);
		c1			= T_index.c1(r);
		c2			= T_index.c2(r);
		c3			= T_index.c3(r);
		c4			= T_index.c4(r);

		if   ~isempty(f1)&&~isempty(snmc1)

			% Data in field 1:
			if isempty(f2)||isempty(snmc2)
				% No data in field 2:

				i_l		= ...
					T_index.f1.(f1)              & ...
					T_index.f2.emptyfields       & ...
					T_index.f3.emptyfields       & ...
					T_index.f4.emptyfields       & ...
					T_index.snmc1.(snmc1)		  & ...
					T_index.snmc2.emptyfields    & ...
					T_index.snmc3.emptyfields    & ...
					T_index.snmc4.emptyfields    & ...
					(T_index.r1==r1)             & ...
					(T_index.r2==r2)             & ...
					(T_index.r3==r3)             & ...
					(T_index.r4==r4)             & ...
					(T_index.c1==c1)             & ...
					(T_index.c2==c2)             & ...
					(T_index.c3==c3)             & ...
					(T_index.c4==c4);
				i_v		= find(i_l);
				kmax		= length(i_v);
				if kmax>1
					r_duplicate(r,1)		= true;
				end

			else

				% Data in field 1 and 2:
				if isempty(f3)||isempty(snmc3)
					% No data in field 3:

					i_l		= ...
						T_index.f1.(f1)              & ...
						T_index.f2.(f2)              & ...
						T_index.f3.emptyfields       & ...
						T_index.f4.emptyfields       & ...
						T_index.snmc1.(snmc1)        & ...
						T_index.snmc2.(snmc2)        & ...
						T_index.snmc3.emptyfields    & ...
						T_index.snmc4.emptyfields    & ...
						(T_index.r1==r1)             & ...
						(T_index.r2==r2)             & ...
						(T_index.r3==r3)             & ...
						(T_index.r4==r4)             & ...
						(T_index.c1==c1)             & ...
						(T_index.c2==c2)             & ...
						(T_index.c3==c3)             & ...
						(T_index.c4==c4);
					i_v		= find(i_l);
					kmax			= length(i_v);
					if kmax>1
						r_duplicate(r,1)		= true;
					end

				else

					% Data in field 1,2 and 3:
					if isempty(f4)||isempty(snmc4)
						% No data in field 4:

						i_l		= ...
							T_index.f1.(f1)              & ...
							T_index.f2.(f2)              & ...
							T_index.f3.(f3)              & ...
							T_index.f4.emptyfields       & ...
							T_index.snmc1.(snmc1)        & ...
							T_index.snmc2.(snmc2)        & ...
							T_index.snmc3.(snmc3)        & ...
							T_index.snmc4.emptyfields    & ...
							(T_index.r1==r1)             & ...
							(T_index.r2==r2)             & ...
							(T_index.r3==r3)             & ...
							(T_index.r4==r4)             & ...
							(T_index.c1==c1)             & ...
							(T_index.c2==c2)             & ...
							(T_index.c3==c3)             & ...
							(T_index.c4==c4);
						i_v		= find(i_l);
						kmax			= length(i_v);
						if kmax>1
							r_duplicate(r,1)		= true;
						end

					else

						% Data in field 1,2,3 and 4:

						i_l		= ...
							T_index.f1.(f1)              & ...
							T_index.f2.(f2)              & ...
							T_index.f3.(f3)              & ...
							T_index.f4.(f4)              & ...
							T_index.snmc1.(snmc1)        & ...
							T_index.snmc2.(snmc2)        & ...
							T_index.snmc3.(snmc3)        & ...
							T_index.snmc4.(snmc4)        & ...
							(T_index.r1==r1)             & ...
							(T_index.r2==r2)             & ...
							(T_index.r3==r3)             & ...
							(T_index.r4==r4)             & ...
							(T_index.c1==c1)             & ...
							(T_index.c2==c2)             & ...
							(T_index.c3==c3)             & ...
							(T_index.c4==c4);
						i_v		= find(i_l);
						kmax		= length(i_v);
						if kmax>1
							r_duplicate(r,1)		= true;
						end

					end

				end

			end

		end

	end

catch ME
	errormessage('',ME);
end

